services:
  rproxy:
    container_name: rproxy
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./rproxy/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
